# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/conding',
                'doc_host': 'https://bonding-curves.github.io',
                'git_url': 'https://github.com/bonding-curves/conding',
                'lib_path': 'conding'},
  'syms': {'conding.core': {'conding.core.foo': ('core.html#foo', 'conding/core.py')}}}
