# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/conding',
                'doc_host': 'https://bonding-curves.github.io',
                'git_url': 'https://github.com/bonding-curves/conding',
                'lib_path': 'conding'},
  'syms': { 'conding.core': {'conding.core.foo': ('tec.html#foo', 'conding/core.py')},
            'conding.dune': { 'conding.dune.DuneWrapper': ('dune.html#dunewrapper', 'conding/dune.py'),
                              'conding.dune.DuneWrapper.__init__': ('dune.html#dunewrapper.__init__', 'conding/dune.py'),
                              'conding.dune.DuneWrapper.refresh_into_dataframe': ( 'dune.html#dunewrapper.refresh_into_dataframe',
                                                                                   'conding/dune.py')},
            'conding.tec': { 'conding.tec.TECDashboard': ('tec.html#tecdashboard', 'conding/tec.py'),
                             'conding.tec.TECDashboard.abc_tributes': ('tec.html#tecdashboard.abc_tributes', 'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_and_supply': ('tec.html#tecdashboard.holders_and_supply', 'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_distribution': ( 'tec.html#tecdashboard.holders_distribution',
                                                                                'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_over_time': ('tec.html#tecdashboard.holders_over_time', 'conding/tec.py'),
                             'conding.tec.TECDashboard.price_chart': ('tec.html#tecdashboard.price_chart', 'conding/tec.py')}}}
