# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/conding',
                'doc_host': 'https://bonding-curves.github.io',
                'git_url': 'https://github.com/bonding-curves/conding',
                'lib_path': 'conding'},
  'syms': { 'conding.core': {'conding.core.foo': ('tec.html#foo', 'conding/core.py')},
            'conding.dune': { 'conding.dune.DuneClient': ('dune.html#duneclient', 'conding/dune.py'),
                              'conding.dune.DuneClient.__init__': ('dune.html#duneclient.__init__', 'conding/dune.py'),
                              'conding.dune.DuneClient.fetch_auth_token': ('dune.html#duneclient.fetch_auth_token', 'conding/dune.py'),
                              'conding.dune.DuneClient.fetch_query_results': ( 'dune.html#duneclient.fetch_query_results',
                                                                               'conding/dune.py')},
            'conding.tec': { 'conding.tec.TECDashboard': ('tec.html#tecdashboard', 'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_and_supply': ('tec.html#tecdashboard.holders_and_supply', 'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_distribution': ( 'tec.html#tecdashboard.holders_distribution',
                                                                                'conding/tec.py'),
                             'conding.tec.TECDashboard.holders_over_time': ('tec.html#tecdashboard.holders_over_time', 'conding/tec.py')}}}
