# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/0_dune.ipynb.

# %% auto 0
__all__ = ['DuneWrapper']

# %% ../nbs/0_dune.ipynb 3
import os
import dotenv
import pandas as pd
from dune_client.types import QueryParameter
from dune_client.client import DuneClient
from dune_client.query import Query

# %% ../nbs/0_dune.ipynb 5
class DuneWrapper:

    def fetch_query_results(self, query_id, params, name="Sample Query"):
        dotenv.load_dotenv()
        dune = DuneClient(os.environ["DUNE_API_KEY"])

        params_formatted = []

        for parameter in params:          
            params_formatted.append(getattr(QueryParameter, parameter["type"] + "_type")(name=parameter["name"], value=parameter["value"]))
        
        if params_formatted:
            query = Query(
                name=name,
                query_id=query_id,
                params=params_formatted
            )
        else:
            query = Query(
                name=name,
                query_id=query_id
            )
        
        df = dune.refresh_into_dataframe(query)
        return df

