# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/0_dune.ipynb.

# %% auto 0
__all__ = ['DuneClient']

# %% ../nbs/0_dune.ipynb 4
class DuneClient:
    
    def __init__(self):
        # Load username and password from .env file.
        dotenv.load_dotenv()
        self.username = os.environ.get('DUNE_USERNAME')
        self.password = os.environ.get('DUNE_PASSWORD')
        self.fetch_auth_token()
        
    def fetch_auth_token(self):
        # Initialize Dune
        dune = DuneAnalytics(self.username, self.password)
        dune.login()
        dune.fetch_auth_token()
        self.dune = dune
    
    def fetch_query_results(self, query_id):
        result_id = self.dune.query_result_id_v3(query_id=query_id)
        data = self.dune.get_execution_result(result_id)['data']['get_execution']['execution_succeeded']
        df = pd.DataFrame(data['data'], columns=data['columns'])
        return df
