# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/1_tec.ipynb.

# %% auto 0
__all__ = ['TECDashboard']

# %% ../nbs/1_tec.ipynb 3
import pandas as pd
import hvplot.pandas
import numpy as np
from .dune import DuneWrapper

# %% ../nbs/1_tec.ipynb 4
class TECDashboard(DuneWrapper):
    "Interface to the TEC Dune Analytics dashboard."

    def holders_distribution(self):
        df = self.refresh_into_dataframe(1898888)
        return df
    
    def holders_and_supply(self):
        df = self.refresh_into_dataframe(1898886)
        return df
    
    def holders_over_time(self):
        df = self.refresh_into_dataframe(1898887)
        return df
    
    def price_chart(self):
        df = self.refresh_into_dataframe(1898885)
        return df
    
    def abc_tributes(self):
        df = self.refresh_into_dataframe(1646841)
        return df
